name: izobility_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  percent_indicator: ^4.2.3
  toggle_switch: ^2.1.0

  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.0
  local_auth: ^2.1.7

  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  go_router: ^10.1.2

  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.1.14

  intl: ^0.18.1
  sliver_tools: ^0.2.12

  qr_flutter: ^4.1.0
  photo_view: ^0.14.0

  mask_text_input_formatter: ^2.5.0
  trust_wallet_core_lib: ^0.0.7+3.0.4

  share_plus: ^7.1.0
  web3dart: ^2.7.1
  hex: ^0.2.0

  flutter_localizations:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  image_editor: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/splash_background.png
    - assets/abi/
    - .env